### PR TITLE
Changes used when building CMSSW

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by peremato** [comment]
Hi Patrick. I do not understand why you are including modules for packages that have already the CMake config files. For example Geant4. The file provided by Geant4 itself is very complete and works very nicely. So, you should not need any other module. In addition, you copied a version from ROOT that is certainly very very obsoleted. Indeed, I do not know why is still there at all.
Other packages such as Davix do not provide the CMake config file but provide the pkgconfig files and therefore again is better to use the provided file than doing it ourselves. For Davix I would use the [FindDavix.cmake](https://github.com/root-project/root/blob/master/cmake/modules/FindDavix.cmake) in ROOT that makes use of PkgConfig.

**Comment by gartung** [comment]
@peremato

**Comment by gartung** [comment]
@peremato FindROOT.cmake is found before ROOTConfig.cmake if find_package(cmaketools) is called  before find_package(ROOT) in a top level CMakeLists.txt. Please consider rename FindROOT.cmake to FindRoot.cmake

**Comment by peremato** [comment]
@gartung we really should remove FindROOT. It applies that same reasoning as for Geant4.

**Comment by gartung** [comment]
@peremato What about EnableROOT5 and EnableROOT6? There is a pull request with an update to EnableROOT5. I will leave it to you to remove the ROOT related files. I will update this PR once that is done.

**Comment by gartung** [comment]
Note I cannot make changes to this repo, hence the pull request.

**Comment by peremato** [comment]
@gartung I have no idea what EnableROOT5 and EnableROOT6 are. Do you use them? My guess is that they can be deleted.

**Comment by gartung** [comment]
They were called from FindROOT.

**Comment by gartung** [comment]
OK I remove those files on this PR.

**Comment by peremato** [comment]
Yes please, and then we see who complains.

**Comment by gartung** [comment]
@peremato I need you to merge this. I don't have write privileges to this repo.

**Pull request merged**
